### ISSUE TITLE
StreamModel not binded (all null)

### ISSUE THREAD

**Issue by russosalv** [ma1f/uploadstream#4]
Hi
i tried to execute your code because i want reuse it throw nuget in my project.
but seens taht there is some issue when i try to perform request from postman or other.

in particular i tried API "stream/binding/model" (line 135 of UploadController.cs)

for post i used Postman setted as followed:
![2020-04-09 10_07_14-Postman](https://user-images.githubusercontent.com/3062596/78872793-16635a80-7a4a-11ea-83a2-fb4523286fdb.png)

I also noted that if you execute 
`return Ok(new { model, streamModel, Files = files });`
line(149 .netcore 3.1 throw in exception because no mapping beetween IFormFile and Json)

can i have your opinion about that?

**Comment by ma1f** [comment]
Previously in 2.2 you could throw the entire IFormFile into the response, since 3.1 with the change from `NewtonSoft.Json` to `System.Json` you can no longer serialise headers by default.
Suggest you change your response to something like the following where you are only selecting the name, not the entire IFormFile object with its' unserialisable properties.
```
return Ok(new { mode, streamModel, Files = files.Select(x => x.name) });
```

**Comment by ma1f** [comment]
The behaviour you are seeing is expected - if you have specified the model in the params `ControllerModelStreamBindingEnabled(UploadModel model)` then it cannot be bound via `var streamModel = await this.StreamFiles<UploadModel>(...)` as it overrides the model and has already read the stream.
These endpoints are simply exploring this model binding behaviour, as it turns out with 3.1 the `DisableFormModelBinding` attribute functionality has changed (not working as expected), which is what the `model/bindingdisabled` endpoint was exploring.

So basically your normal expected usage is as follows - this does the model binding and model validation that would be normally be performed.
```
[HttpPost("stream/binding")]
public async Task<IActionResult> ControllerStreamBindingEnabled() {
    var model = await this.StreamFiles<StreamModel>(async x => {
        ...
    });
)
```

I have updated the api to display the results correctly (note creating an anonymous object without the `Headers` property to serialise the json)
```
return Ok(new {
    model = new {
        model.Name,
        model.Description,
        Files = model.Files.Select(x => new {
            x.Name,
            x.FileName,
            x.ContentDisposition,
            x.ContentType,
            x.Length
        })
    },
    streamModel,
    Files = files.Select(x => new {
        x.Name,
        x.FileName,
        x.ContentDisposition,
        x.ContentType,
        x.Length
    })
});
```
