### ISSUE TITLE
StreamFiles not hit in core 3.1

### ISSUE THREAD

**Issue by AnamikaDe85** [ma1f/uploadstream#6]
`Hi,`

I recently upgrading my solution to 3.1 core from 2.2. I used to use the 2.2.0 version of Uploadstream with framework 2.2 with no model binding and used streaming, worked perfectly fine.

While upgrading, upgraded to 3.1.1 version of the package . Now the StreamFiles method is not at all hit and bypasses the upload logic in it.

Its used like

Await this.StreamFiles( async x=> {
(using var a = x.OpenFileStream())
{

....,, logic

}

}

Please advice.

**Comment by ma1f** [comment]
Can you post your entire controller method including attributes if any.
Since 3.1 it appears there have been changes around `[DisableFormModelBinding]` where is doesn't appear to be required any more, and if you have a model in your controller method I believe that will cause the `StreamFiles` method to skip (as the request body has already then been read).

**Comment by AnamikaDe85** [comment]
Hi,

Thanks for the reply. Please find the custom code below..Which is in core 3.1 now and am using package 3.1.1.It does not throw me any exception,just that it bypasses the StreamFIles call.

.Also one more thing, I would like to know how we can handle negative scenarios and return from within the StreamFiles Method .

    [Route("api/[controller]")]
    [Produces("application/json")]
    [ApiController]
    public class AController : BaseController
    {	

        [HttpPost("Upload")]
        [ResponseCache(NoStore = true, Duration = 0, Location = ResponseCacheLocation.None)]
        [Authorize]
        [DisableRequestSizeLimit]
        [Consumes("multipart/form-data")]
        [DisableFormModelBinding]
        public async Task<CustomResponse> Upload(int a, int b = 0, int c = 0)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    BadRequest(ModelState);
                }
				
		await this.StreamFiles(async x =>
                {
                    using (var stream = x.OpenReadStream())//open in coming stream for reading and storing.
                    {
                      ----logic 
		     }
					   
                }
				
	   }
	}
		
   }

**Comment by AnamikaDe85** [comment]
Hi,

Could you please help me on this , actually kinda timeboxed here.Would be grateful.

Anamika

**Comment by ma1f** [comment]
Apologies, thought I had responded to this.
The issue is with your parameters `Upload(int a, int b = 0, int c = 0)` - by specifying a model here you force the model binding, this results in the request having already been read by the time it hits `StreamFiles`.
If you wish to bind to a model, use `var model = await this.StreamFiles<MyModel>(async formFile => { .. });`
